//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acerodon.App.AcerodonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Query", Namespace="http://schemas.datacontract.org/2004/07/Acerodon.Repository")]
    [System.SerializableAttribute()]
    public partial class Query : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Acerodon.App.AcerodonService.Filter[] FiltersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Acerodon.App.AcerodonService.Sort[] SortsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Acerodon.App.AcerodonService.Filter[] Filters {
            get {
                return this.FiltersField;
            }
            set {
                if ((object.ReferenceEquals(this.FiltersField, value) != true)) {
                    this.FiltersField = value;
                    this.RaisePropertyChanged("Filters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Page {
            get {
                return this.PageField;
            }
            set {
                if ((this.PageField.Equals(value) != true)) {
                    this.PageField = value;
                    this.RaisePropertyChanged("Page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rows {
            get {
                return this.RowsField;
            }
            set {
                if ((this.RowsField.Equals(value) != true)) {
                    this.RowsField = value;
                    this.RaisePropertyChanged("Rows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Acerodon.App.AcerodonService.Sort[] Sorts {
            get {
                return this.SortsField;
            }
            set {
                if ((object.ReferenceEquals(this.SortsField, value) != true)) {
                    this.SortsField = value;
                    this.RaisePropertyChanged("Sorts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Filter", Namespace="http://schemas.datacontract.org/2004/07/Acerodon.Repository")]
    [System.SerializableAttribute()]
    public partial class Filter : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sort", Namespace="http://schemas.datacontract.org/2004/07/Acerodon.Repository")]
    [System.SerializableAttribute()]
    public partial class Sort : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Acerodon.App.AcerodonService.Sort.SortOrder OrderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Acerodon.App.AcerodonService.Sort.SortOrder Order {
            get {
                return this.OrderField;
            }
            set {
                if ((this.OrderField.Equals(value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.DataContractAttribute(Name="Sort.SortOrder", Namespace="http://schemas.datacontract.org/2004/07/Acerodon.Repository")]
        public enum SortOrder : int {
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Ascending = 0,
            
            [System.Runtime.Serialization.EnumMemberAttribute()]
            Descending = 1,
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcerodonService.DataService")]
    public interface DataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Get", ReplyAction="http://tempuri.org/DataService/GetResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyCustomer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Company))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmploymentStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmployeeRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Project))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Gender))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Milestone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.MilestoneTask))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Task))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.TaskStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.ICompany))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IPerson))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.ITask))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.App.AcerodonService.Query))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.App.AcerodonService.Filter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.App.AcerodonService.Filter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.App.AcerodonService.Sort[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.App.AcerodonService.Sort))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.App.AcerodonService.Sort.SortOrder))]
        Acerodon.GenericDataContract.Types.AcerodonDataContract Get(Acerodon.GenericDataContract.Types.AcerodonDataContract contract, Acerodon.App.AcerodonService.Query query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Get", ReplyAction="http://tempuri.org/DataService/GetResponse")]
        System.Threading.Tasks.Task<Acerodon.GenericDataContract.Types.AcerodonDataContract> GetAsync(Acerodon.GenericDataContract.Types.AcerodonDataContract contract, Acerodon.App.AcerodonService.Query query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Add", ReplyAction="http://tempuri.org/DataService/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyCustomer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.ICompany))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Company))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmploymentStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmployeeRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IPerson))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Project))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Gender))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.MilestoneTask))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.ITask))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Task))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Milestone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.TaskStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.User))]
        bool Add(Acerodon.Model.Interface.IEntity entry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Add", ReplyAction="http://tempuri.org/DataService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(Acerodon.Model.Interface.IEntity entry);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceChannel : Acerodon.App.AcerodonService.DataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Acerodon.App.AcerodonService.DataService>, Acerodon.App.AcerodonService.DataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Acerodon.GenericDataContract.Types.AcerodonDataContract Get(Acerodon.GenericDataContract.Types.AcerodonDataContract contract, Acerodon.App.AcerodonService.Query query) {
            return base.Channel.Get(contract, query);
        }
        
        public System.Threading.Tasks.Task<Acerodon.GenericDataContract.Types.AcerodonDataContract> GetAsync(Acerodon.GenericDataContract.Types.AcerodonDataContract contract, Acerodon.App.AcerodonService.Query query) {
            return base.Channel.GetAsync(contract, query);
        }
        
        public bool Add(Acerodon.Model.Interface.IEntity entry) {
            return base.Channel.Add(entry);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(Acerodon.Model.Interface.IEntity entry) {
            return base.Channel.AddAsync(entry);
        }
    }
}
