//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acerodon.App.AcerodonService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AcerodonService.DataService")]
    public interface DataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/GetList", ReplyAction="http://tempuri.org/DataService/GetListResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyCustomer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Project[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Project))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Milestone[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Milestone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Task[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Task))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Gender))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmploymentStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.TaskStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmployeeRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Filter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Company))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyCustomer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Query))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Filter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Sort[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Sort))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Sort.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.GenericDataContract.Types.ItemDataContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.ICompany))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IPerson))]
        Acerodon.GenericDataContract.Types.ListDataContract GetList(Acerodon.GenericDataContract.Types.ListDataContract contract, Acerodon.Model.Query query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/GetList", ReplyAction="http://tempuri.org/DataService/GetListResponse")]
        System.Threading.Tasks.Task<Acerodon.GenericDataContract.Types.ListDataContract> GetListAsync(Acerodon.GenericDataContract.Types.ListDataContract contract, Acerodon.Model.Query query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/GetItem", ReplyAction="http://tempuri.org/DataService/GetItemResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.User))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyCustomer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Project[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Project))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Milestone[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Milestone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Task[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Task))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Gender))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmploymentStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.TaskStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmployeeRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Filter))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Company))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyCustomer[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Query))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Filter[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Sort[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Sort))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Sort.SortOrder))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.GenericDataContract.Types.ListDataContract))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IEntity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.ICompany))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IPerson))]
        Acerodon.GenericDataContract.Types.ItemDataContract GetItem(Acerodon.GenericDataContract.Types.ItemDataContract contract, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/GetItem", ReplyAction="http://tempuri.org/DataService/GetItemResponse")]
        System.Threading.Tasks.Task<Acerodon.GenericDataContract.Types.ItemDataContract> GetItemAsync(Acerodon.GenericDataContract.Types.ItemDataContract contract, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Add", ReplyAction="http://tempuri.org/DataService/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Category))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyCustomer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.ICompany))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Company))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Customer))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IActivity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Milestone))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Task))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Interface.IPerson))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Gender))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Employee))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmploymentStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.TaskStatus))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.Project))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.CompanyPosition))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.EmployeeRole))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Acerodon.Model.User))]
        bool Add(Acerodon.Model.Interface.IEntity entry);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DataService/Add", ReplyAction="http://tempuri.org/DataService/AddResponse")]
        System.Threading.Tasks.Task<bool> AddAsync(Acerodon.Model.Interface.IEntity entry);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DataServiceChannel : Acerodon.App.AcerodonService.DataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<Acerodon.App.AcerodonService.DataService>, Acerodon.App.AcerodonService.DataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Acerodon.GenericDataContract.Types.ListDataContract GetList(Acerodon.GenericDataContract.Types.ListDataContract contract, Acerodon.Model.Query query) {
            return base.Channel.GetList(contract, query);
        }
        
        public System.Threading.Tasks.Task<Acerodon.GenericDataContract.Types.ListDataContract> GetListAsync(Acerodon.GenericDataContract.Types.ListDataContract contract, Acerodon.Model.Query query) {
            return base.Channel.GetListAsync(contract, query);
        }
        
        public Acerodon.GenericDataContract.Types.ItemDataContract GetItem(Acerodon.GenericDataContract.Types.ItemDataContract contract, System.Guid id) {
            return base.Channel.GetItem(contract, id);
        }
        
        public System.Threading.Tasks.Task<Acerodon.GenericDataContract.Types.ItemDataContract> GetItemAsync(Acerodon.GenericDataContract.Types.ItemDataContract contract, System.Guid id) {
            return base.Channel.GetItemAsync(contract, id);
        }
        
        public bool Add(Acerodon.Model.Interface.IEntity entry) {
            return base.Channel.Add(entry);
        }
        
        public System.Threading.Tasks.Task<bool> AddAsync(Acerodon.Model.Interface.IEntity entry) {
            return base.Channel.AddAsync(entry);
        }
    }
}
